---
image_size: &IMAGE_SIZE 256
channel_size: &CHANNEL_SIZE 1
model:
    class: 'resnet_18'
    params:
        input_shape: [*CHANNEL_SIZE, *IMAGE_SIZE, *IMAGE_SIZE]
        num_outputs: &NUM_OUTPUTS 2
image_pipeline:
    extractor:
        class: 'Key'
        params:
            key_array: 'image_path_256'
    loader:
        class: 'GrayscaleImage'
    transformers:
        - class: 'ResizeImage'
          params:
            size: [*IMAGE_SIZE, *IMAGE_SIZE]
        - class: 'NormalizeImage'
        - class: 'ReshapeImage'
          params: 
            shape: [*IMAGE_SIZE, *IMAGE_SIZE, *CHANNEL_SIZE]
label_pipeline:
    extractor:
        class: 'Key'
        params: 
            key_array: 'density'
    transformers:
        - class: 'BinarizeLabel'
